# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
 - GHCVER=7.4.2 CABALVER=1.22
 - GHCVER=7.6.3 CABALVER=1.22
 - GHCVER=7.8.4 CABALVER=1.22 #ghc 7.8 versions, see note about alex and happy
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head CABALVER=1.22

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version
 - cabal update
 - cabal install -j -O2 packdeps

install:
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal test
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated
 - cabal --version | grep --quiet '1.22';
   if [ $? -eq 0 ]; then
      find . -name '*.cabal' | xargs cabal exec packdeps;
   fi

# The following scriptlet checks that the resulting source distribution can be built & installed
 - function install_from_tarball {
   export SRC_TGZ=$(cabal-$CABALVER info . | awk '{print $2 ".tar.gz";exit}') ;
   if [ -f "dist/$SRC_TGZ" ]; then
      cabal install "dist/$SRC_TGZ" -v2;
   else
      echo "expected 'dist/$SRC_TGZ' not found";
      exit 1;
   fi
   }
 - install_from_tarball

# Check the fgl-arbitrary sub-package
 - cd fgl-arbitrary
 - cabal sandbox init
 - cabal sandbox add-source ../
 - cabal install --dependencies-only
 - cabal configure
 - cabal build
 - cabal check
 - cabal sdist
 - install_from_tarball

matrix:
  fast_finish: true
  allow_failures:
    - env: GHCVER=head CABALVER=1.22 # see section about GHC HEAD snapshots
